/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.SaleGroup.SellerGUI.Component;

import DAL.DataModels.ChiTietHoaDon;
import DAL.DataModels.SanPham;
import javax.swing.JButton;
import javax.swing.JSpinner;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author huykh
 */
public class OrderItem extends RoundPanel{ 
    private SanPham sp;

    /**
     * Creates new form OrderItem
     */
    public OrderItem() {
        initComponents();
        SpinnerNumberModel model1 = new SpinnerNumberModel(1, 1, 50, 1);
        productOrderQuantity.setModel(model1);
        jspinerEventAdd();
    }
    
    public OrderItem(SanPham sp) {
        this.sp = sp;
        initComponents();
        SpinnerNumberModel model1 = new SpinnerNumberModel(1, 1, 50, 1);
        productOrderQuantity.setModel(model1);
        setGuiText(sp.getTenSP(),sp.getHinhAnh(),sp.getGiaTien());
        jspinerEventAdd();
    }
    
    private void setGuiText(String productName, String imgPath, long productPrice){
        this.productOrderName.setText("<html>"+productName);
        this.productOrderImage.setImagePath(imgPath);
        this.productOrderPrice.setText(Long.toString(productPrice));
        this.productOrderTotal.setText(Long.toString(productPrice*getQuantity()));
    }
    
    //Chua bao gom ma hoa don
    public ChiTietHoaDon getChiTietHoaDon(){
        return new ChiTietHoaDon(this.sp.getMaSP(), 0, Integer.valueOf(this.productOrderQuantity.getValue()+""), this.sp.getGiaTien());
    }
    
    //Truyen ma hoa don bang ham
    public ChiTietHoaDon getChiTietHoaDon(int maHD){
        return new ChiTietHoaDon(this.sp.getMaSP(), maHD, Integer.valueOf(this.productOrderQuantity.getValue()+"") , this.sp.getGiaTien());
    }

    public SanPham getSp() {
        return sp;
    }

    public void setSp(SanPham sp) {
        this.sp = sp;
    }
    
    public int getMaSP(){
        return this.sp.getMaSP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productOrderImage = new GUI.SaleGroup.SellerGUI.Component.ImagePanel();
        productOrderName = new javax.swing.JLabel();
        productOrderTotal = new javax.swing.JLabel();
        productOrderQuantity = new javax.swing.JSpinner();
        btnRemoveOrderItem = new javax.swing.JButton();
        productOrderPrice = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(240, 92));
        setRadius(30);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productOrderImage.setBackground(new java.awt.Color(255, 255, 255));
        productOrderImage.setImage(new javax.swing.ImageIcon(getClass().getResource("/GUI/SaleGroup/LoginGui/Image/icons8-user-100.png"))); // NOI18N

        javax.swing.GroupLayout productOrderImageLayout = new javax.swing.GroupLayout(productOrderImage);
        productOrderImage.setLayout(productOrderImageLayout);
        productOrderImageLayout.setHorizontalGroup(
            productOrderImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        productOrderImageLayout.setVerticalGroup(
            productOrderImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(productOrderImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 60));

        productOrderName.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        productOrderName.setForeground(new java.awt.Color(29, 186, 218));
        productOrderName.setText("<html>Nước ngọt cocacola 500ml + ly đá rat ngon");
        add(productOrderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 140, 30));

        productOrderTotal.setBackground(new java.awt.Color(255, 255, 255));
        productOrderTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        productOrderTotal.setForeground(new java.awt.Color(29, 186, 218));
        productOrderTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productOrderTotal.setText("30.000");
        add(productOrderTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 100, 20));
        add(productOrderQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 80, -1));

        btnRemoveOrderItem.setBackground(new java.awt.Color(255, 153, 153));
        btnRemoveOrderItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRemoveOrderItem.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveOrderItem.setText("X");
        btnRemoveOrderItem.setBorder(null);
        btnRemoveOrderItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveOrderItemActionPerformed(evt);
            }
        });
        add(btnRemoveOrderItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 30, 20));

        productOrderPrice.setForeground(new java.awt.Color(29, 186, 218));
        productOrderPrice.setText("30.000");
        add(productOrderPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 140, 20));

        jLabel4.setForeground(new java.awt.Color(29, 186, 218));
        jLabel4.setText("Giá:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 30, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveOrderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveOrderItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveOrderItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemoveOrderItem;
    private javax.swing.JLabel jLabel4;
    private GUI.SaleGroup.SellerGUI.Component.ImagePanel productOrderImage;
    private javax.swing.JLabel productOrderName;
    private javax.swing.JLabel productOrderPrice;
    private javax.swing.JSpinner productOrderQuantity;
    private javax.swing.JLabel productOrderTotal;
    // End of variables declaration//GEN-END:variables

    private void jspinerEventAdd() {
         final JTextField jtf = ((JSpinner.DefaultEditor) productOrderQuantity.getEditor()).getTextField();
         jtf.getDocument().addDocumentListener(new DocumentListener() {
             @Override
             public void insertUpdate(DocumentEvent e) {
                 showUpdateTotalPrice();
             }

             @Override
             public void removeUpdate(DocumentEvent e) {
                 showUpdateTotalPrice();
             }

             @Override
             public void changedUpdate(DocumentEvent e) {
                 showUpdateTotalPrice();
             }
         });
           ((DefaultEditor) productOrderQuantity.getEditor()).getTextField().setEditable(false);
         
    }
    
    protected void showUpdateTotalPrice(){
        this.productOrderTotal.setText(Long.toString(this.sp.getGiaTien()*getQuantity()));
        System.out.println(this.sp.getGiaTien()*getQuantity());
    }
    
    public void changeQuantity(long amout){
        this.productOrderQuantity.setValue(amout);
        showUpdateTotalPrice();
    }
    
    public long getQuantity(){
        return Long.valueOf(this.productOrderQuantity.getValue()+"");
    }
    
    public JButton getButtonRemove(){
        return btnRemoveOrderItem;
    }
    

}
