
create database SieuThiMini;
use SieuThiMini;

create table NHACUNGCAP(
    MANCC varchar(50) not null primary key,
    TENNCC varchar(50),
    DIACHI varchar(100),
    SDT varchar(11),
    EMAIL varchar(50),
    IS_DELETED boolean
);

create table LOAISANPHAM(
    MALOAI int not null primary key,
    TENLOAI varchar(50),
    MOTA varchar(100)
);

create table SANPHAM(
    MASP int not null primary key,
    TENSP varchar(50),
    MOTA varchar(100),
    SOLUONG int,
    HINHANH varchar(100),
    GIATIEN bigint,
    MALOAI int,
    MANCC varchar(50),
    IS_DELETED boolean
);

create table MAKHUYENMAI(
    MAKM varchar(50) not null primary key,
    LOAIKM int,
    MOTA varchar(100),
    NGAYBD datetime,
    NGAYKT datetime,
    GIATRITOITHIEU bigint,
    KMTOITHIEU bigint,
    KMTOIDA bigint,
    PTGIAM int,
    SOLUOTSD int,
    IS_DELETED boolean
);

create table CHITIETKM_NCC(
    MAKM varchar(50) not null,
    MANCC varchar(50) not null,
    PRIMARY KEY (MAKM, MANCC)
);

create table CHITIETKM_SP(
    MAKM varchar(50) not null,
    MASP INT not null,
    PRIMARY KEY (MAKM, MASP)
);

create table PHIEUHUY(
    MAPHIEU int not null primary key,
    NGAYLAP datetime,
    -- MANV int,
    IS_DELETED boolean
);

create table CTPHIEUHUY_SP(
    MAPHIEU int not null,
    MASP int not null,
    SOLUONG int,
    PRIMARY KEY (MAPHIEU, MASP)
);

create table PHIEUNHAP(
    MAPHIEU int not null primary key,
    NGAYLAP datetime,
    -- MANV int,
    IS_DELETED boolean
);

create table CTPHIEUNHAP_SP(
    MAPHIEU int not null,
    MASP int not null,
    SOLUONG int,
    PRIMARY KEY (MAPHIEU, MASP)
);



ALTER TABLE SANPHAM ADD CONSTRAINT FK_SANPHAM_LOAISANPHAM FOREIGN KEY (MALOAI) REFERENCES LOAISANPHAM(MALOAI);
ALTER TABLE SANPHAM ADD CONSTRAINT FK_SANPHAM_NHACUNGCAP FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC);

ALTER TABLE CHITIETKM_NCC ADD CONSTRAINT FK_CHITIETKM_NCC_MAKM FOREIGN KEY (MAKM) REFERENCES MAKHUYENMAI(MAKM);
ALTER TABLE CHITIETKM_NCC ADD CONSTRAINT FK_CHITIETKM_NCC_NHACUNGCAP FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC);

ALTER TABLE CHITIETKM_SP ADD CONSTRAINT FK_CHITIETKM_SP_SANPHAM FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP);
ALTER TABLE CHITIETKM_SP ADD CONSTRAINT FK_CHITIETKM_SP_MAKM FOREIGN KEY (MAKM) REFERENCES MAKHUYENMAI(MAKM);

ALTER TABLE CTPHIEUNHAP_SP ADD CONSTRAINT FK_CHITIETPHIEUNHAP_SP_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP);
ALTER TABLE CTPHIEUNHAP_SP ADD CONSTRAINT FK_CHITIETPHIEUNHAP_SP_PHIEUNHAP FOREIGN KEY (MAPHIEU) REFERENCES PHIEUNHAP(MAPHIEU);

ALTER TABLE CTPHIEUHUY_SP ADD CONSTRAINT FK_CHITIETPHIEUHUY_SP_PHIEUHUY FOREIGN KEY (MAPHIEU) REFERENCES PHIEUHUY(MAPHIEU);
ALTER TABLE CTPHIEUHUY_SP ADD CONSTRAINT FK_CHITIETPHIEUHUY_SP_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP);

ALTER TABLE PHIEUNHAP ADD CONSTRAINT FK_PHIEUNHAP_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);
ALTER TABLE PHIEUHUY ADD CONSTRAINT FK_PHIEUHUY_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);